### ISSUE TITLE
Write certdb files somewhere outside of www

### ISSUE THREAD

**Issue by oremj** [mozilla/betachannel#49]
We should write viewable cert.db files outside of the package root i.e., make it configurable.

```
Error: EACCES, permission denied '/opt/betafox/betafox/www/cert9.db'
    at Object.fs.symlinkSync (fs.js:730:18)
    at /opt/betafox/betafox/server/lib/keygen.js:53:16
    at Array.forEach (native)
    at /opt/betafox/betafox/server/lib/keygen.js:48:49
    at ChildProcess.exithandler (child_process.js:645:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:753:16)
    at Process.ChildProcess._handle.onexit (child_process.js:820:5)
```

**Comment by ozten** [comment]
Fixed in bc62d21.

'cert9.db', 'key4.db', 'pkcs11.txt' are served directly from NodeJS.
